language: java
jdk: oraclejdk8

cache:
  directories:
    - travis-phantomjs

before_install:
  - gem install sass
  - pip install --user codecov
  - phantomjs --version
  - mkdir travis-phantomjs && PHANTOM_EXISTS=false
  - if [ $PHANTOM_EXISTS = 'false' ]; then wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi
  - if [ $PHANTOM_EXISTS = 'false' ]; then tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs; fi
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
  - phantomjs --version

after_success:
  - codecov
  - chmod 755 ./scripts/deploy.sh
  - ./scripts/deploy.sh