language: java
jdk: oraclejdk8

cache:
  directories:
    - travis-phantomjs

before_install:
  - gem install sass
  - pip install --user codecov
  - phantomjs --version
  - ls -lisa travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
  - phantomjs --version

after_success:
  - codecov
  - chmod 755 ./scripts/deploy.sh
  - ./scripts/deploy.sh