language: java
jdk: oraclejdk8

cache:
  directories:
    - travis-phantomjs
    - triplog-client/node_modules
    - triplog-client/public/bower_components

before_install:
  - npm install -g npm
  - gem install sass
  - pip install --user codecov
  - chmod 755 ./scripts/*
  - ./scripts/installPhantomJS.sh

after_success:
  - codecov
  - ./scripts/deploy.sh